### ISSUE TITLE
Get sidebar to display meetup titles rather than addresses

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#11]
- Get sidebar to display meetup titles rather than addresses

**Comment by tog22** [comment]
Nice work! Peter and I'll handle getting this onto the live repo.

**Comment by peterhurford** [comment]
https://github.com/tog22/eaforum/commit/e72a2d4ac57079f800696b8ba675659a5afeef60

**Comment by peterhurford** [comment]
Reopening until we get it into Trike's master.

**Comment by peterhurford** [comment]
Submitted to Trike: https://github.com/tricycle/eaforum/pull/7
