### ISSUE TITLE
Link to list of regular meetups from meetups page

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#13]
It'd be good for http://effective-altruism.com/meetups/ to link to this list, which is at http://effectivealtruismhub.com/groups

**Comment by arichard4** [comment]
Pull request submitted- is this what you had in mind?

**Comment by peterhurford** [comment]
https://github.com/tog22/eaforum/pull/15

**Comment by peterhurford** [comment]
Submitted to Trike: https://github.com/tricycle/eaforum/pull/7

**Comment by tog22** [comment]
@peterhurford doesn't seems like you actually included this in https://github.com/tricycle/eaforum/pull/7 (it might also be worth rewording).

**Comment by peterhurford** [comment]
@tog22 Good catch -- Submitted in https://github.com/tricycle/eaforum/pull/10
