### ISSUE TITLE
Sidebar doesn't work when zooming on Firefox

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#2]
When you zoom in on the EA forum this sidebar gets pushed below the main content, as attached. Can you figure out why this is and what CSS change we can make to fix it?

![Img](http://i.imgur.com/Q57FVIU.png)

**Comment by peterhurford** [comment]
As in the screenshot, the main content area gets pushed off to the right, and the sidebar gets pushed below it, due to being right floated. This is in Mac Firefox (doesn't happen in Chrome).

It's triggered at all window sizes, with the same FF version.  **The problem only happens when you zoom in** (command +, View > Zoom).

**Comment by JoshuaDavid** [comment]
Adding the following line to the #content selector seems to fix the problem. I'm not entirely sure why that's necessary though.

``` css
    clear: both;
```

``` css
#content {
    float: left;
    clear: both;
    padding: 30px 0 0 32px;
    width: 710px
}
```

Tomorrow I'll have a look at the code base and see where that's defined, and then make a pull request.

**Comment by peterhurford** [comment]
Excellent progress!

**Comment by peterhurford** [comment]
Joshua David told me: "I figured out the cause of one of the issues, but I'll need to get the VM set up to see how to fix it and make a pull request. I'm adding a new Ubuntu VM tonight, and tomorrow I'll figure out how to get it serving the EA forum."  I told him he could talk to Tom for help.

**Comment by tog22** [comment]
Nice work! Peter and I'll handle getting this onto the live repo.

**Comment by peterhurford** [comment]
Joshua's fix: https://github.com/tog22/eaforum/commit/81f61f524628e0a6fece903b3d8ee8aa3301cad9
Patrick's fix: https://github.com/tricycle/eaforum/pull/5

Reopening until we get this into Trike master.

**Comment by patbl** [comment]
Lol, I just realized that both the issues I worked on already had fixes.

**Comment by patbl** [comment]
For me, it also happened also when zooming out. (Though if I zoomed out far enough, the problem would go away.)

**Comment by peterhurford** [comment]
Closing because we've submitted a PR to Trike. https://github.com/tricycle/eaforum/pull/5
