### ISSUE TITLE
feature request: automatically appear online when returning to the site

### ISSUE THREAD

**Issue by RyanCarey** [tog22/eaforum#23]
If, rather than having to log in at each visit, people stay logged in (or have the option of doing so), there would be a lower barrier to participation, and this might improve user experience and increase volume of content.

**Comment by arichard4** [comment]
I'm not sure what you mean by this. Do you mean that if you login, then refresh the page or go elsewhere and return, you will stay logged in? AFAICT this is already the site's behavior, at least for me.

**Comment by RyanCarey** [comment]
Oh, my bad, I just have to check 'remember me' and it works on all platforms.
