### ISSUE TITLE
Remove GiveWell or GoodVentures from 'Recently on EA Blogs' rss

### ISSUE THREAD

**Issue by RyanCarey** [tog22/eaforum#25]
Currently, lots of the posts in 'Recently on EA Blogs' are duplicates, because they have been dual-posted on GiveWell and GoodVentures.

Currently, the top two most recent posts are:
- Geomagnetic Storms: Using Extreme Value Theory to Gauge the Risk
- Geomagnetic storms: Using extreme value theory to gauge the risk.

About 90% of posts from GiveWell/Goodventures are duplicates.
I guess the easiest way to manage this would be to remove one of the organisations, probably GoodVentures, from our feed.

**Comment by arichard4** [comment]
This is something currently specified in development.ini, which is in the .gitignore and which will require it being remove from the .gitignore or being manually changed.

**Comment by tog22** [comment]
I'll deal with that again.

**Comment by tog22** [comment]
I asked Trike to make the actual change (outside the git repo), we can submit a PR for the change within the repo later.

**Comment by peterhurford** [comment]
Submitted to Trike as https://github.com/tricycle/eaforum/pull/19

**Comment by peterhurford** [comment]
I'm still keeping this issue open just to confirm.

**Comment by arichard4** [comment]
I've looked in the javascript generating the sidebar, and it no longer checks goodventures.
