### ISSUE TITLE
Replace meetup functionality on the EA Forum

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#27]

**Comment by patbl** [comment]
I wonder whether it's worth having meetups on the EA forum. Currently, it's not really being used. I guess that could mean either that it needs more work, or that we should cut our losses, or that people just aren't aware of it.

Facebook seems so much better for advertising events like this. There are people who don't use Facebook, though.

It might be worth talking to leaders of local groups about why they don't use the meetups feature and whether they think improvements would be worthwhile.

**Comment by tog22** [comment]
Good point, thanks for raising this. We should definitely consider cutting
our losses. I talk to local group leaders often so will ask them about the
EA Forum feature next mass email I send out to them all. What do you think
@peterhurford and @ryancarey ?

**Comment by RyanCarey** [comment]
Yeah I think it's of neutral to mildly negative value atm. Not sure if it
can be integrated with Facebook and am happy to hear input on what should
be done.

**Comment by tog22** [comment]
We had Alex Flint try looking at FB integration in another github issue and
it turned out to be quite difficult, so realistically I think we should
assume that's a no go. Assuming everyone's happy with this I'll go ahead
and ask the group organizers for their thoughts about the feature and
whether they'd find it useful enough to use (perhaps after we make any
changes they suggest). Then I'll pass on what they say and we can decide
whether to hide it - you could make the final call on that Ryan.

**Comment by peterhurford** [comment]
I think it's best that features related to meetups are driven by the demand of meetup organizers.

**Comment by peterhurford** [comment]
It also seems plausible that if we do meetup-related work it might be best done in the EA Hub or on Meetups.com.

**Comment by tog22** [comment]
Yep, agreed - having it driven by the demand of meetup organizers makes
sense, and it seems like my plan of asking in the newsletter is a decent
way to go about that. I wouldn't be surprised if using Meetup.com and
Facebook is the way groups end up going, but ultimately they'll decide that
organically.

**Comment by tog22** [comment]
So as planned I asked all the local group organisers about this via the
inter-LEAN newsletter we send them. I told them we were thinking of
dropping it and would like their input on this/suggestions for other
approaches at
https://www.facebook.com/groups/localea/permalink/1181364495226225/ . The
consensus was for dropping it; no one disagreed. There were one or two
feasible suggestions for replacements.

What do you think @RyanCarey?

**Comment by RyanCarey** [comment]
Yes, I'm not opposed to hiding it. What are the replacements?

**Comment by tog22** [comment]
The most popular suggestion from the comment thread and emails was to replace it with a link to http://eahub.org/groups as the groups link to their Facebook/Meetup.com groups there, and can pick out the best place to find upcoming events. Presumably the best place for this'd be a bullet point under 'Getting Started' - what do you think of doing that?

**Comment by RyanCarey** [comment]
Ok link "Meetup groups" there.

**Comment by tog22** [comment]
Neat, that was simple to resolve! @arichard4 could you submit a pull request direct to Trike for this (it's pretty simple so shouldn't need checking by Peter)? Say if not!

**Comment by patbl** [comment]
We should probably also hide this (on http://effective-altruism.com/prefs/):

![screenshot 2016-02-07 20 17 53](https://cloud.githubusercontent.com/assets/1735266/12878341/f097e226-cdd7-11e5-86cd-928adca46cc4.png)

**Comment by tog22** [comment]
Good shout, I see you hid that preference option in your commit.

**Comment by patbl** [comment]
Closed by https://github.com/tricycle/eaforum/pull/30.
