### ISSUE TITLE
Zoom on phone is very broken

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#28]
Whenever I browse the EA forum on my phone (which I do daily), I get a very zoomed in view and I cannot zoom out.  My phone is an iPhone 5C and I use Chrome.  I miss being able to browse the forum on my phone. :(

**Comment by arichard4** [comment]
Seems to be due to chrome- Safari works fine on my iPhone 4.
Seems not to be due to the changes to mobile viewing in issue #7; reverting them didn't change anything.

Will look into this further.

**Comment by peterhurford** [comment]
I was actually using Safari; not Chrome.

**Comment by arichard4** [comment]
Hmmm.
When you say you miss it, do you mean that zoom used to work? (Before the changes made as part of issue #7 ?)

**Comment by peterhurford** [comment]
I can't confirm any causal relationship with #7, but 6 days ago when I logged onto the forum it was normal sized, now it is enlarged and I can't zoom out.  When it was normal sized I couldn't zoom out either, it just didn't matter.

**Comment by william-r-s** [comment]
Zoom also doesn't work on Chrome (I'm pretty sure it worked before, not sure of timeline) and Firefox on Android (Samsung Galaxy S4).

**Comment by arichard4** [comment]
Setting user-scalable doesn't appear to change anything.
Per Chrome emulator, this appears to not work on lesswrong and main & mobile reddit as well, so it's not something unique to our code base. I'm currently stumped, so I've submitted this as an issue to the main reddit repo. Hopefully their engineers will figure this out.

**Comment by william-r-s** [comment]
On my Android (Samsung Galaxy S4), this issue doesn't occur on lesswrong or desktop reddit, just on http://www.effective-altruism.com/

**Comment by peterhurford** [comment]
FWIW, LessWrong works just fine on my phone.  EA Forum still does not.

**Comment by arichard4** [comment]
...
Can someone else check on your computer, using Chrome emulator (Control+Shift+i in Chrome) to emulate the iPhone 4, iPhone 5, or Galaxy S4 on lesswrong or reddit to see if zooming works?

**Comment by william-r-s** [comment]
Used chrome emulator, saw the same behaviour as my phone. Zoom (holding
shift and moving the mouse) works on lesswrong.com, not on
effective-altruism.com

**Comment by arichard4** [comment]
Welp. I'm not sure what's going on with my laptop and phone, then, but I seem to be unable to replicate this problem.

**Comment by william-r-s** [comment]
I took a quick look at the page source, and it looks like the culprit is
<meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
I downloaded a static copy of the page, replicated the zoom problem in the chrome emulator, and then changed it to:
<meta name="viewport" content="width=device-width minimum-scale=0.25 maximum-scale=2.0">
which allowed zooming in in the chrome emulator.

**Comment by tog22** [comment]
We added `<meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">` in commit https://github.com/tog22/eaforum/commit/6e14cf5341f54d418afb2b064d23a65d267cb3d2 . We had tested it (on my part using Chrome emulator) but obviously missed this, my bad.

@arichard4 how do you think we can change this?

**Comment by arichard4** [comment]
Yep, sorry, it was my changes in issue #7 that broke zooming.
Pretty sure the given changes work OK; at least per my testing.

**Comment by arichard4** [comment]
Of interest is whether issue #7 remains solved in this branch; my model of what was going wrong there would suggest that setting width=device-width should break the comment box again, but I just tested it and it seems to work OK.

**Comment by tog22** [comment]
What do you suggest I do Alex? Deploy William's suggested change? It's a
shame we don't have a testing server we could access from phones.

**Comment by RyanCarey** [comment]
Yes, just noticed this, and had it raised with me by a user.

**Comment by arichard4** [comment]
Yes

**Comment by tog22** [comment]
PR submitted: https://github.com/tricycle/eaforum/pull/13 . As I said on Slack, `paster` is broken on my local install so I can't test it just now, but others have and it's simple enough that I can see it _should_ work and can't break anything too bad.

**Comment by tog22** [comment]
@wrsaunde Trike have now deployed my PR to http://effective-altruism.com/. Can you confirm it's fixed this issue?

cc @arichard4 just FYI.

**Comment by william-r-s** [comment]
It's fixed (chrome and firefox on Android)

**Comment by RyanCarey** [comment]
Android works well for me, as do comments.

**Comment by peterhurford** [comment]
Yep, working for me now as well.  Good work! :+1:
