### ISSUE TITLE
Social sharing buttons for articles

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#3]
The EA Forum already has more sessions than in any previous month, and seems to be trending up month on month. The overall trend is upwards, but only gradually so. Content is still flowing in, which is good. But if the forum is to reach a critical mass so that it achieves deeper engagement with a wider group of users, it would help to drive up activity in other ways. Over a third of our traffic currently comes from social media, and one imagines this could be a lot greater if Tweet and Like Buttons were present on each post, and the number of such shares were displayed. More readership makes more people want to write there, hopefully creating a virtuous circle.

**Comment by tog22** [comment]
Pull request submitted (combined with readme west submitted (combined with readme change from Ryan - https://github.com/tog22/eaforum/issues/3 )

**Comment by peterhurford** [comment]
@tog22 I can't find the PR.

**Comment by peterhurford** [comment]
Reopening until we get it into Trike master.

**Comment by tog22** [comment]
It's in (though ideally we'd vertically align it more carefully).
