### ISSUE TITLE
Automate Testing

### ISSUE THREAD

**Issue by arichard4** [tog22/eaforum#35]
Testing is currently entirely manual, except for the unused wiki. The manual testing steps are specified in test/manual.txt; however, the manual testing steps are badly out of date- for example, meetups are not tested at all. This is all bad.

**Comment by tog22** [comment]
:+1:

I and (principally) @peterhurford have been doing some manual testing with the current workflow:
1. Get a complete set of changes we're considering approving into a branch in this community development fork.
2. Test them on our local vagrant boxes.
3. Submit a PR from that branch to trike master (the live production repo).

Updating test/manual.txt might be the most worthwhile low hanging fruit, but @peterhurford can work this out, chatting with you if you're up for it/think that'd be good.

**Comment by peterhurford** [comment]
Longer-term, we really do need to start thinking about how to add automated tests.

**Comment by patbl** [comment]
The code is so hairy and poorly understood that our best bet would probably be to create a QA server and use Selenium to run integration tests. This seems that it'd be a bit of work, and it would probably be facilitated with help from Trike.

If we don't plan on making many changes to the forum, though, automated testing seems unnecessary.

**Comment by peterhurford** [comment]
@patbl :+1:

**Comment by patbl** [comment]
I'm going to close this because it's not clear that this is worthwhile or what the next steps would be.

**Comment by tog22** [comment]
Good call, thanks for the initiative Patrick.
