### ISSUE TITLE
Trouble logging in to the EA forum when moving between pages (Daniel Filan)

### ISSUE THREAD

**Issue by RyanCarey** [tog22/eaforum#39]
Daniel Filan: "I'm having trouble logging in to the EA forum. When I'm on
effective-altruism.com I can log in (and remain logged in), but when I
click on an article, I appear to no longer be logged in. If I go back to
the main page, I see myself as logged in again. Do you have any idea why
this should be the case, or how to fix it?"

I've not noticed this personally Any thoughts? I've linked Dan here to provide clarifications as required.

**Comment by dfilan** [comment]
Possibly relevant: before noticing this, I changed my password.

**Comment by dfilan** [comment]
Actually, the problem seems to have disappeared now. I'm not sure why this would be the case - the only thing that has changed is the passage of time and which wireless network I am connecting from (problem was on university wifi, am currently using home wifi). I can see if the problem re-appears when I go back to uni tomorrow.

**Comment by tog22** [comment]
I suspect this is the already-noted issue of people appearing logged in
only when they refresh pages. @patbl, can you remind @peterhurford and I
what the current status on fixing this is? :)

On Wednesday, 16 September 2015, Daniel Filan notifications@github.com
wrote:

> Actually, the problem seems to have disappeared now. I'm not sure why this
> would be the case - the only thing that has changed is the passage of time
> and which wireless network I am connecting from (problem was on university
> wifi, am currently using home wifi). I can see if the problem re-appears
> when I go back to uni tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tog22/eaforum/issues/39#issuecomment-140714622.

## 

## 

I receive a lot of email and limit my time spent on it, so may take a while
to see or reply to messages; I may be able to reply more quickly to emails
with an indication of timeframes (e.g. with 'urgent' in the subject line).

Contact information: http://bit.ly/tagoogleplus

**Comment by peterhurford** [comment]
I think if people were happy with Patrick's solution on https://github.com/tog22/eaforum/issues/8, we can submit that to Trike.

**Comment by tog22** [comment]
I'm happy with it if @patbl is, are you good to handle it when you have time @peterhurford ?

**Comment by tog22** [comment]
Closing - @dfilan seems to find this sufficiently hard to replicate that I suggest we wait to see if we get more reports of this or encounter it ourselves after the PR is merged.

**Comment by dfilan** [comment]
At university again, cannot replicate the problem.

**Comment by tog22** [comment]
OK, thanks for letting us know Daniel, post here if you ever find a way to replicate it :smile:
