### ISSUE TITLE
Ability for moderator to delete forum posts

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#4]
- Ability for moderator to delete forum posts (I currently am only able to moderate comments, and I need to ask Trike to directly access the mysql database if it is necessary to delete a post, which probably will eventually cause a problem)

**Comment by peterhurford** [comment]
https://github.com/tog22/eaforum/pull/17

**Comment by peterhurford** [comment]
Submitted to Trike as https://github.com/tricycle/eaforum/pull/8
