### ISSUE TITLE
Make the blue bar less abrasive

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#42]
Someone mentions: "are there any plans to change the comments on the EA Forum? I find the thick blue border around each of the nested comments a bit abrasive and unnecessarily large. This is definitely a minor, minor issue, but thought I'd bring it up, and didn't know where the best place to mention it was."

**Comment by peterhurford** [comment]
A suggestion is to only blue the top-most new comment rather than each one.

**Comment by patbl** [comment]
Fixed by https://github.com/tricycle/eaforum/pull/23.
