### ISSUE TITLE
Meetup http://effective-altruism.com/meetups/3y is crashing

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#43]
None of the other meetups seem to be broken.

**Comment by peterhurford** [comment]
I imagine the meetup was just broken via our meetups fix, so we can probably just delete the meetup and move on.  ...Or bury it over time in new meetups.

**Comment by tog22** [comment]
Bury it over time, I deliberately set its date as soon so it'll disappear shortly

**Comment by tog22** [comment]
it was actually a fake meetup i made as a test

**Comment by peterhurford** [comment]
:+1:

**Comment by arichard4** [comment]
Other new ones being added are confirmed as working: 
http://effective-altruism.com/meetups/40

**Comment by tog22** [comment]
Woohoo! :dancers: :tada:
