### ISSUE TITLE
Now that spam is on the rise, we should have a report spam feature

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#44]

**Comment by arichard4** [comment]
This already exists in the reddit codebase, changing 'report=False' to 'report=True' in line 111 of r2/r2/templates/link.html _should_ (in theory) provide this for posts. (Should this also be present for comments? I believe that this will also be a one-line change.)

I can implement and test this by Sunday, definitely.

**Comment by peterhurford** [comment]
@arichard4 Have I told you lately that you're like _the best_?

**Comment by tog22** [comment]
Ditto! :star2: :heart_eyes:

**Comment by arichard4** [comment]
Update: so I did technically implement it; however, the base implementation was not helpful at all. Instead, I intend to just make a button that has the user send a message to [somebody] with the comment's url already and report message already filled in.

(The base implementation was broken in at least 2 different ways and also AFAICT didn't actually send a regular message to the mods- the only effect I noticed was to put a bolded message beside the up/downvote buttons.)

**Comment by tog22** [comment]
Yeah, that seems simple - I assume you mean a button with a `mailto:` link.

**Comment by peterhurford** [comment]
@arichard4 Are you up for finishing this? A new rise in spam has made this the top requested feature!

**Comment by arichard4** [comment]
I'm working on it; in Chicago for a conference, so don't have time to finish it right now, but ETA should be sometime next week.

**Comment by peterhurford** [comment]
@arichard4 You're in Chicago? We should meet up!

**Comment by arichard4** [comment]
Initial draft is now up on mine; apologies for the delay due to my laptop breaking. My todo list before sending it to Trike is under arichard4/eaforum@62966d69abc373c91f8799a6c7f9fe22095ec22a

That commit also has a fairly full explanation of my backend changes. For the frontend, I did a crude photoshop to produce icons from 'exclamation.png' and put them into the sprites png. It all still needs work to make it prettier.

**Comment by tog22** [comment]
@patbl can you take a look and give your thoughts? Thanks!

**Comment by patbl** [comment]
I left a couple of minor suggestions. It looks fine.

**Comment by peterhurford** [comment]
Thanks @arichard4 @patbl !

**Comment by arichard4** [comment]
OK, seems done. @patbl  @tog22  (/anybody), what is the process now?

**Comment by arichard4** [comment]
FYI, here is what it looks like.

Here are the buttons for reporting posts and comments:
![2016-05-20-162829_1366x768_scrot](https://cloud.githubusercontent.com/assets/7397740/15444661/f89d651a-1ea7-11e6-88c5-42c6ef5fc938.png)

They turn blue and have a popup on mouseover:
![2016-05-20-162945_1366x768_scrot](https://cloud.githubusercontent.com/assets/7397740/15444679/19c538a8-1ea8-11e6-93a6-ba7a4e5888fe.png)

Once clicked, they ask the user to verify that they want to report the thing:
![2016-05-20-162838_1366x768_scrot](https://cloud.githubusercontent.com/assets/7397740/15444662/f89fd58e-1ea7-11e6-8761-02fd3457dd2e.png)

If the user clicks yes, a report is emailed and it says 'reported'; if they click no, it goes back to the way it was before:
![2016-05-20-163229_1366x768_scrot](https://cloud.githubusercontent.com/assets/7397740/15444721/86ecf4ca-1ea8-11e6-866d-cdb4bfadd25b.png)

I haven't been able to test this the way it would be in production, but this is the sort of email the contact@effectivealtruism.com _should_ be receiving:
![2016-05-20-162849_1366x768_scrot](https://cloud.githubusercontent.com/assets/7397740/15444663/f8a0d7e0-1ea7-11e6-8347-ce7a1b93a4d6.png)

I remain mildly concerned with the UI- I'm not sure if the button will make sense for a report button, and the mouseover button still looks ugly. But I think it's usable for now.

**Comment by peterhurford** [comment]
@arichard4 That looks pretty good! Gets the job done and I think the UI is understandable enough. 👍 

I think if @patbl @tog22 approve we could go ahead and send this to Trike. I can also check over email with the mods that this is what they'd like.

**Comment by patbl** [comment]
Am I correct in my understanding that this involves fairly minor code changes? I think I already reviewed the relevant code, except for the bit changing one of the arguments of a method call. That part looks fine too.

It would be easier to see the entire scope of the changes if there were a pull request, but Trike might take the existence of a pull request as meaning that the code is OK to deploy. I wonder whether we should have some convention for marking pull requests as "under review" or "ready to deploy." We could simply use those or similar phrases in the pull-request title.

**Comment by arichard4** [comment]
I'll submit a pull request to tog22/eaforum.

**Comment by arichard4** [comment]
I've submitted a pull request to patbl/eaforum.

**Comment by tog22** [comment]
Looks good to go! Since Patrick found it hard to see what the changes were, would you be up for submitting a pull request direct to https://github.com/tricycle/eaforum by the end of the month Alex? If not, we will, as we normally have 😄

**Comment by tog22** [comment]
PS: replied before seeing your last message with the PR to patbl/eaforum, but let me know anyway!

**Comment by tog22** [comment]
Code looks simple to me - have you confirmed that the other icons from https://github.com/arichard4/eaforum/blob/3db294f638b596b806071c9545c856f153141161/r2/r2/public/static/icons.png still work?

**Comment by arichard4** [comment]
Not sure what you mean by 'still work'- you can see how the page looks in the above screencaps, I can't see any unrelated changes

**Comment by arichard4** [comment]
I'm planning on submitting a pull request for this on Friday, if nobody objects/has any comments.
(Should I send this to the email list as well?)

**Comment by tog22** [comment]
No, just go for it!

By 'still work', I mean that the other icons still show correctly. Good point, the screencap makes me confident that they will.

**Comment by peterhurford** [comment]
@arichard4 Seems like we have signoff from everyone so LGTM. Make that PR and I can get Trike to merge.

**Comment by arichard4** [comment]
Confirmed as working by Rebecca
