### ISSUE TITLE
EA Forum search box doesn't work

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#45]

**Comment by tog22** [comment]
Are you OK to look into this Alex? :smile:

**Comment by tog22** [comment]
@patbl - how about you? (cc @peterhurford just FYI)

**Comment by patbl** [comment]
I'll take a look.

**Comment by tog22** [comment]
Great, thanks!

**Comment by patbl** [comment]
:point_up: Here's the fix.

**Comment by tog22** [comment]
They've merged this but the search button is still hidden, could you unhide it @patbl ? Maybe one of us commented it out?

**Comment by patbl** [comment]
This needs to be merged for it to show up: https://github.com/tricycle/eaforum/pull/24

**Comment by tog22** [comment]
Ah gotcha, I've chased our main Trike contact there.

**Comment by patbl** [comment]
Looks like it's fixed.
