### ISSUE TITLE
When you're logged in and you click your profile link, the logged-in portion of the header disappears

### ISSUE THREAD

**Issue by patbl** [tog22/eaforum#46]
When you're logged in and you click your name in the header, the bit of the header with your name and karma and a sign-out link disappears:

![before](https://cloud.githubusercontent.com/assets/1735266/11332397/380525be-917a-11e5-9b84-bc1381a6e4d6.png)

![after](https://cloud.githubusercontent.com/assets/1735266/11332400/3c33da36-917a-11e5-996f-bb2cde1fbfd2.png)

**Comment by patbl** [comment]
[This](https://github.com/patbl/eaforum/commit/4e1bc0454cfe63d34a594bc04211222d728b5b55) seems to fix it. I wonder whether there's a reason for the existing complexity. It seems like an unnecessarily indirect way of getting things to behave in the desired fashion.

**Comment by tog22** [comment]
> I wonder whether there's a reason for the existing complexity. It seems like an unnecessarily indirect way of getting things to behave in the desired fashion.

Not sure if this is the explanation here, but Trike have said they really don't understand the codebase and have had to make lots of edits with hacks (like rewriting the page with JS).

**Comment by patbl** [comment]
FIxed by that :point_up:.
