### ISSUE TITLE
Escape key should close log-in modal

### ISSUE THREAD

**Issue by patbl** [tog22/eaforum#48]
From https://github.com/tricycle/eaforum/issues/28:

I tried to upvote a comment.

I was then greeted by a modal window that asked me to login.

As a user I felt like I should be able to hit escape to exit this modal window, but this was not the case.

I may get to offering a pull request with these tweaks, but I'm only presently a Ruby/Rails developer and not yet really familiar with Python or Django.

Thanks and best wishes,
Jay

**Comment by tog22** [comment]
Thanks for copying across Patrick!
