### ISSUE TITLE
After upvoting and signing in, user should be redirected to main post page (not dedicated comment page)

### ISSUE THREAD

**Issue by patbl** [tog22/eaforum#49]
From https://github.com/tricycle/eaforum/issues/28:

I tried to upvote a comment.

I was then greeted by a modal window that asked me to login.

As a user I expected to be taken back to the post page after login (i.e., the post on which the comment I was trying to upvote was a comment). Instead I was taken to a dedicated page for the comment itself.

I may get to offering a pull request with these tweaks, but I'm only presently a Ruby/Rails developer and not yet really familiar with Python or Django.

Thanks and best wishes,
Jay

**Comment by patbl** [comment]
I spent several hours trying to fix this. As I recall, the problem was that when I fixed it, #8 resurfaced. So it might be necessary to find a better solution to #8 before this can be fixed.

**Comment by tog22** [comment]
I think we can leave it for now until (or rather unless) a volunteer who wouldn't be doing something else surfaces to take it on.

**Comment by peterhurford** [comment]
@patbl None of your recent PRs addressed this, right?

**Comment by patbl** [comment]
Right. I think I did look into this and it seemed as though it would have be a bit of effort to implement (more than I thought it would be). I can't remember why, though.

**Comment by patbl** [comment]
@peterhurford and anyone else: I have a pull request (https://github.com/tricycle/eaforum/pull/52) to address this issue, but I'm not satisfied with it. It attempts position the comment at the top of the viewport, but if there's not enough room (e.g., if there aren't any comments below it), it won't be able to do this.

It would be possible to visually highlight the comment, perhaps with an animation. Maybe I could use CSS transitions. Facebook highlights the background of the comment in yellow, which then fades. I could try to do something similar. Dunno whether it's worth the effort, though.

What do you all think?

**Comment by tog22** [comment]
I think tricycle#52 is acceptable - colouring the upvoted comment would be nicer, but I reckon it's only worth doing if you have a bit of spare EA time and feel like it. 😄
