### ISSUE TITLE
Make a button on user's page to send a message (LessWrong has a link that does this)

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#5]
- Make a button on user's page to send a message (LessWrong has a link that does this)

**Comment by arichard4** [comment]
As is, i.e. in the reddit codebase, the page requires a moderately ugly captcha to send messages. Is there any real need for this? Should I just totally eliminate the captcha to send messages, or make it prettier?

**Comment by arichard4** [comment]
Looked at this further; the captcha is only displayed for users with 0 karma, which seems reasonable. Pull request submitted.

**Comment by peterhurford** [comment]
https://github.com/tog22/eaforum/pull/16

**Comment by peterhurford** [comment]
Submitted to Trike https://github.com/tricycle/eaforum/pull/9
