### ISSUE TITLE
Add 'Guide' link at bottom

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#53]
Replace 'Powered by reddit' at the bottom with `<a href="https://eahub.org/forum/guide">Guide</a>`

**Comment by tog22** [comment]
Would you be OK to do this @arichard4?

**Comment by patbl** [comment]
It's a bit odd to have this information on a different website.

I think "FAQ" might be more easily understood than "Guide."

**Comment by tog22** [comment]
Good call about switching to 'Forum FAQ'.

Yeah, that was just cos it was quicker to make there. But thinking about it
you think it's worth it you could make it a regular post on the forum
(pasting in the bit about EA Profile links) and link to it. Either way,
would you be up for doing 3 things fist?

1) adding a question about the relationship to the fb group and if time
other discussion venues.

2) adding a link to
http://wiki.effectivealtruismhub.com/index.php?title=List_of_EA_discussion_venues
somewhere

3) emailing Ryan to ask if it looks OK, ccing me and Peter

**Comment by patbl** [comment]
I could do those things, but I'll be on holiday for the next week so probably wouldn't get to it till sometime after that.

**Comment by tog22** [comment]
No worries, understood! No one is going to do it sooner after all. :smile:

**Comment by tog22** [comment]
That's totally fine, as before no one else is going to do these things
sooner/otherwise!

**Comment by peterhurford** [comment]
Looks like this is almost wrapped up!

**Comment by peterhurford** [comment]
Guide is ready - http://www.effective-altruism.com/ea/vm/ea_forum_faq/ - but it still needs to be linked.

**Comment by patbl** [comment]
I'll take care of this when I get home today.

**Comment by peterhurford** [comment]
I see https://github.com/tricycle/eaforum/pull/35 was merged by Trike, but it hasn't taken effect. I assume they need to re-deploy?

**Comment by patbl** [comment]
I was wondering the same thing. It could also be that the footer is cached. (I haven't checked.)

**Comment by patbl** [comment]
But the change to the RSS-feed title isn't evident either, so they probably haven't deployed any of the changes yet.

**Comment by peterhurford** [comment]
I'll follow up in a few days and if it isn't fixed them, I'll ping them to deploy.

**Comment by tog22** [comment]
IIRC the change to the RSS feeds can be delayed.

**Comment by patbl** [comment]
​I still don't see the RSS-feed or footer changes.​

**Comment by tog22** [comment]
I've asked Michael Webb (`@moggyboy`) in https://github.com/tricycle/eaforum/pull/35

**Comment by patbl** [comment]
This was fixed, but I just noticed that the spacing around the pipes seems inconsistent. 

<img width="662" alt="screenshot 2016-05-11 20 50 10" src="https://cloud.githubusercontent.com/assets/1735266/15203634/7514904a-17ba-11e6-9682-10c3de762a1e.png">

Pretty minor, but easy to fix.

**Comment by tog22** [comment]
Cool - to be crystal clear, will you try fixing this at some point, or should I get someone else to?

**Comment by patbl** [comment]
Here's the fix: https://github.com/tricycle/eaforum/pull/43
