### ISSUE TITLE
OpenPhil should be in the list of blogs

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#56]

**Comment by tog22** [comment]
Where? If you mean the RSS feed I think it already is, right @patbl / @arichard4 ?

**Comment by patbl** [comment]
I tried fixing this in tricycle/eaforum#31, but it seems that the `development.ini` setting isn't what controls this in production. There are other discrepancies between the list in `development.ini` and the generated JavaScript in production, namely in the feeds for Overcoming Bias, Slate Star Codex, Jeff's blog, and Open Phil.

```
// development.ini:
feedbox_urls = http://www.overcomingbias.com/feed, 
http://slatestarcodex.com/feed, 
http://reflectivedisequilibrium.blogspot.com/feeds/posts/default, 
http://feeds.feedburner.com/TheGivewellBlog?format=xml, 
http://80000hours.org/blog/feed.atom, 
http://rationality.org/blog/feed/, 
http://feeds.feedburner.com/EverydayUtilitarian?format=xml, 
http://www.jefftk.com/news.rss, 
http://www.givinggladly.com/feeds/posts/default, 
http://www.openphilanthropy.org/blog/rss

// production JavaScript:
var urls = ["http://slatestarcodex.com/tag/rationality/feed", 
"http://reflectivedisequilibrium.blogspot.com/feeds/posts/default", 
"http://feeds.feedburner.com/TheGivewellBlog?format=xml",
 "http://80000hours.org/blog/feed.atom", 
"http://rationality.org/blog/feed/", 
"http://feeds.feedburner.com/EverydayUtilitarian?format=xml", 
"http://www.givinggladly.com/feeds/posts/default", 
"http://www.jefftk.com/news/giving.rss"];
```

**Comment by patbl** [comment]
I imagine this is something that we'd have to ask someone at Trike to update.

**Comment by tog22** [comment]
That's correct. @arichard4 knows what we need to ask Trike to update - what is that Alex?

**Comment by peterhurford** [comment]
@arichard4 @tog22 @patbl I can contact Trike. What should I say?

**Comment by patbl** [comment]
My guess is that they need to make the same change I made in
https://github.com/tricycle/eaforum/pull/31/files in another file (perhaps
named `production.ini.erb`).

**Comment by tog22** [comment]
@arichard4 knows. I'm just emailing him ccing you guys to check.

**Comment by arichard4** [comment]
Has anything happened on this?

**Comment by patbl** [comment]
Not to my knowledge!

**Comment by peterhurford** [comment]
@tog22 @arichard4 What are the next steps on this?

**Comment by arichard4** [comment]
The feedbox is generated from a list of rss urls in development.ini. development.ini is in the .gitignore; it is generated from development.ini.erb in the build process, but can't be directly updated via git. (It's in the .gitignore because it also contains stuff involving debugging, ports, etc.) To get the changes to live, Trike will need to manually update r2/development.ini. Specifically, they will need to append ", http://www.openphilanthropy.org/blog/rss" to the end of feedbox_urls, as was done for development.ini.erb in this commit:

https://github.com/tricycle/eaforum/pull/31/files

**Comment by peterhurford** [comment]
Contacted Trike.

**Comment by arichard4** [comment]
Trike just removed development.ini from the .gitignore, which works too. I'll push the open phil addition; we all now need to use the same development.ini (e.g. use the same port)

**Comment by peterhurford** [comment]
@arichard4 👍

**Comment by peterhurford** [comment]
I don't think this worked out...

**Comment by patbl** [comment]
Maybe we should cut our losses.

**Comment by michaelwebb76** [comment]
Sorry @peterhurford I haven't been tracking this issue. Production gets deployed with a `production.ini` that is kept in a separate, private repo. This is the thing that needed to be updated with the additional URL. I've just updated and deployed it.

**Comment by patbl** [comment]
Wowowowow, it's fixed!

![](https://media2.giphy.com/media/12Ykt1s73rhhWE/giphy.gif)

**Comment by patbl** [comment]
Wowowowow, it's fixed!

**Comment by peterhurford** [comment]
Thanks @moggyboy! 👍
