### ISSUE TITLE
301 redirect ea-forum.trikeapps.com URLs to effective-altruism.com

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#58]
e.g. http://ea-forum.trikeapps.com/ea/ns/my_cause_selection_michael_dickens/

**Comment by tog22** [comment]
@ryancarey - who did you talk to on the Trike end about this way back when?

**Comment by RyanCarey** [comment]
Michael Webb I think

**Comment by peterhurford** [comment]
I think this is something Trike would have to do?

**Comment by RyanCarey** [comment]
Isn't this request a bit pointless? The ea-forum.trikeapps was only ever
promoted for a few weeks over 1-2 years ago.

Ryan Carey | bioinformatics student | medical resident

**Comment by tog22** [comment]
@peterhurford I already asked Trike.

@careyryan the value is that ea-forum.trikeapps is still the _only_ result
that shows up on Google for some articles, and that's bad for SEO.

**Comment by arichard4** [comment]
Verified as working
