### ISSUE TITLE
Add click-tracking to links worth tracking

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#59]
To do this you add `onclick="_gaq.push(['_trackEvent', 'Text description 1', 'Text description 2']);"` to `<a>` elements.  

As part of this task you'd come up with a list, which it might be good to run past me (and any others) here. 
# Examples 

'Recently on EA Blogs' links, for all of which you'd make 'Text description 1' read 'Recently on EA Blogs link' (i.e. saying the same thing), and for which it's probably not worth giving a unique 'Text description 2'.

Adding a different event for each link in Getting Started and all the clickable interface elements in the top bar would be good.

**Comment by tog22** [comment]
Hey Patrick, if you're ever not up for one of these tasks just say and unassign them!

**Comment by patbl** [comment]
Another option would be to use [Heap Analytics](https://heapanalytics.com/), which would let us track everything. The free plan covers 5,000 sessions a month, or 50,000 if we stick this somewhere:

![image](https://cloud.githubusercontent.com/assets/1735266/14943356/855f67ea-0f8b-11e6-8430-23918c88f307.png)

We currently have about 12,000 sessions a month according to Google Analytics, so 5,000 sessions would give us a pretty good sampling.

There wouldn't really be any harm in using both Heap and GA for click tracking.

**Comment by tog22** [comment]
If you think that'd give us data you thought you could personally turn into
something action-relevant then go for it, but without the image :)

**Comment by peterhurford** [comment]
@tog22 @patbl What do you think the priority of this should be?

**Comment by patbl** [comment]
Adding Google Analytics tracking to specific links seems not easy. Generating the links in the "Getting Started" sidebar, for example, involves at least the following classes: `Reddit`, `PaneStack`, `LinkBox`, `Wrapped`. I'm not sure how these work, but it's not a matter of just inserting an `onclick` attribute into a few anchor elements—there are several layers of abstraction.

Heap has the advantage of tracking every click by default. I think we should try it and see whether 5,000 sessions gives us enough data. It would also be possible to get Google Analytics to work, but I'm not sure it's worth the effort. I can give you all access to the Heap data if we go ahead with it.

**Comment by tog22** [comment]
Ah, didn't realise it was so abstracted. Heap was a good call, I'm glad to
see you submitted a PR for that!

**Comment by patbl** [comment]
Seems to be working. Send me your e-mail address if you want access (pbrinichlanglois@gmail.com).

<img width="537" alt="screenshot 2016-06-07 13 46 32" src="https://cloud.githubusercontent.com/assets/1735266/15874046/44f4e43a-2cb6-11e6-9acd-b026fa834f7b.png">

**Comment by tog22** [comment]
Awesome! Are you still up for turning this date into something
action-relevant for us, if only perhaps in a few months? Please add me on
tog.ash@gmail.com either way - ideally letting me add others if that's easy.

**Comment by patbl** [comment]
You've been added. You should receive an e-mail.
