### ISSUE TITLE
Make an RSS/XML feed of meetups that automatically collates from whatever places allow this (e.g. meetup.com) [step towards automatically posting them on FB/Forum/etc.]

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#6]
The original request was:
- auto-posting of meetups from Meetup.com or hooking it up with some 3rd party software that can post to Facebook and the EA Forum simultaneously.

I've revised it to this more modest 1st step - see comments below. This means it should require no handover - someone can jump right into it. Though they can @-tag @alexflint if it seems worth drawing on his prior research.

**Comment by alexflint** [comment]
I will be working on this during the EA workathon today

**Comment by alexflint** [comment]
One way to tackle this will be:
- Use zapier.com. Create a "zap" that polls the meetup.com API every 15 minutes and posts new events when they are created to a REST endpoint at effective-altruism.com.
- Create a REST endpoint (maybe /meetup/import) that accepts a title, event date, description, and so on, and creates a nicely formatted meetup entry.
- Zapier also has support for facebook posting, so it should be easy to post meetup details to the facebook group.

Notes:
- The free tier with zapier only permits 100 events per month. This should be enough for a while but we will have to eventually either pay $20/mo or build our own system to poll the meetup API dramatically. More billing info: https://zapier.com/app/settings/billing/plan/123
- Meetup API docs: http://www.meetup.com/meetup_api/ (unfortunately meetup only has a regular pull API; there is no way to "subscribe" to events afaict)

**Comment by alexflint** [comment]
Hmm unfortunately zapier does not support posting to facebook groups (only ordinary timeline posts): https://zapier.com/help/facebook-pages/#can-i-use-facebook-groups-with-zapier

One solution may be to write the facebook API integration ourselves at the eaforum end of the endpoint described above (i.e. the handler for /meetup/import is also responsible for posting to the facebook group through the facebook API)

Another may be to look for a zapier-like service that does support facebook groups.

A third option would be to write our own meetup poller and avoid zapier altogether.

**Comment by tog22** [comment]
Just creating an XML feed of all meetups would be a good first step, before we work out where we can then post them - we may have to give up on Facebook.

**Comment by peterhurford** [comment]
:+1:

**Comment by tog22** [comment]
Does creating that XML feed seem viable @alexflint ? How long do you think it'd take you if so? :smile:

**Comment by peterhurford** [comment]
@tog22 I'm assuming @alexflint isn't available to do this.

**Comment by tog22** [comment]
> @tog22 I'm assuming @alexflint isn't available to do this.

Indeed. @imbenclifford - here's a shovel-ready task that you can assign to people or not, as you decide. I suggest we just leave it at that.

**Comment by patbl** [comment]
I worked on this a while ago as a standalone app. I might work on it some more, but it doesn't seem that closely related to the EA Forum.

**Comment by tog22** [comment]
Agreed, I'm closing that issue for this reason. Could you assign yourself an Asana task to carry on working on it (as and when you feel like it), so we can keep track of that?

**Comment by patbl** [comment]
Sure, here it is: https://app.asana.com/0/49980280880475/88613261675880

**Comment by tog22** [comment]
Thanks! That link doesn't seem to work though?

**Comment by patbl** [comment]
Sorry; it was private.
