### ISSUE TITLE
Add 'Other Resources' to 'Getting Started' menu

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#60]
Please add `<a href="/ea/xd/ea_links/">Other Resources</a>` to the bottom of the 'Getting Started' menu, under 'Meetups'.

**Comment by tog22** [comment]
Note to self (Tom): tell Anne complice is here on forum plus EA Hub home page when done, ccing Ryan.

**Comment by arichard4** [comment]
Verified as working in production
