### ISSUE TITLE
Pressing "Save and continue" publishes post.

### ISSUE THREAD

**Issue by jeremiahbuddha** [tog22/eaforum#61]
There are two buttons available when creating a new post, "Submit" and "Save and Continue". My impression is that "Save and continue" should save your work but not publish your post, and that the "Submit" button is what you use to actually publish it to the forum. Is this right?

I just did a short test and "Save and continue" is publishing posts, at least from my setup (Chrome Version 50.0.2661.94 (64-bit)). Can someone else confirm whether this is the expected behavior and if it can be repeated in your browsers?

**Comment by tog22** [comment]
Thanks for reporting this! We're actually planning to change this following discussion at https://github.com/tog22/eaforum/issues/54#issuecomment-217753747 . I've just assigned the person who was talking about it to do so.

**Comment by jeremiahbuddha** [comment]
Yep, that's exactly the issue, sounds like you guys have a handle on it. Thanks!

**Comment by peterhurford** [comment]
Thanks @jeremiahbuddha. I'll close this and we can talk about it on https://github.com/tog22/eaforum/issues/54#issuecomment-217753747.
