### ISSUE TITLE
Change UI for saving drafts of and publishing articles

### ISSUE THREAD

**Issue by patbl** [tog22/eaforum#62]
[Copied from https://github.com/tog22/eaforum/issues/54#issuecomment-217753747]

There are two buttons, "Submit" and "Save and continue," that as far as I can tell do almost the same thing. The only difference is that "Submit" redirects you to the article URL, while "Save and continue" keeps you on the "Submit article" page.

![confusing-ui](https://cloud.githubusercontent.com/assets/1735266/15101081/5f635276-153b-11e6-81d0-13bbfea3a2bc.png)

I would expect "Save and continue" to simply save your article, not make it public. But to control that behavior, you have to use a drop-down menu that typically has only two options: "Drafts for so-and-so" and "EA Forum." And it seems that the drop-down menu defaults to "EA Forum." So if you don't notice that drop-down menu, or you don't understand what it does, you're likely to publish an article before it's ready.

Here are some ideas for a better UI:
- Get rid of the drop-down menu.
- Have two buttons, "Save" and "Publish." It might be good to display a confirmation dialog when someone clicks "Publish" in case they fat-finger it.
- After the article is published, there should be two buttons, "Update" and "Unpublish."

There should probably be a "Delete" button on the edit page as well. It's weird that you can only delete it by going to the public URL.
#61 is a retroactive duplicate.

**Comment by tog22** [comment]
Are you planning to assign yourself to this @patbl ? No worries if not! 

Whoever does this, please implement Patrick's bulleted suggestions for the UI changes.

**Comment by patbl** [comment]
Maybe, but it would probably be in a couple of weeks. I'll assign myself if I start working on it. Someone else can grab it if they want to.

**Comment by tog22** [comment]
@arichard4, in case you're interested in doing a little forum work 😄

**Comment by arichard4** [comment]
I'll take a look, will self-assign if I am

**Comment by tog22** [comment]
That works well, thanks!

**Comment by patbl** [comment]
The tag and "Post to" form elements have been removed.

The UI overhaul introduced [this issue](https://github.com/tog22/eaforum/issues/76), which I'll fix soon.

Other loose ends can have their own issues.

**Comment by tog22** [comment]
Great work!
