### ISSUE TITLE
Article bodies can be blank

### ISSUE THREAD

**Issue by patbl** [tog22/eaforum#63]
You can submit an article with just a title and no body.

We could require a non-blank (at least one-character) body, or a certain number of characters or words.

This would require displaying an error message if the requirement weren't met.

**Comment by arichard4** [comment]
I would prefer not to make this change:
- I've just spent an hour or so looking through the codebase and starting doing this; it will be fairly complicated to do correctly (i.e. through the forum's existing validation code) (call it 5-6 more hours to get it working well enough to submit)
- It seems like there is no use case for this; in fact, AFAICT reddit today doesn't have this. (See the decorators for POST_submit: https://github.com/reddit/reddit/blob/387becd9e4db4f6fa5f5b547f35e2cd6eb67f1a9/r2/r2/controllers/api.py)
- There are conceivable situations where somebody could want to submit a post with no content; e.g. an open thread

If nobody objects, I will close this
