### ISSUE TITLE
The Recently on EA Blogs "Poorly Organized Thoughts on Funding" link is broken

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#64]
Not sure what happened there...?

**Comment by peterhurford** [comment]
It looks like the correct link should be http://www.jefftk.com/p/poorly-organized-thoughts-on-funding

**Comment by arichard4** [comment]
Jeff's rss feed gives links as relative urls:

http://www.jefftk.com/news/giving.rss

When we display the link, it is completed relative to our base url, not his.

Edit: See also:

http://www.feedvalidator.org/check.cgi?url=www.jefftk.com%2Fnews%2Fgiving.rss

**Comment by peterhurford** [comment]
Cool - sounds like I should bug him about it...

**Comment by peterhurford** [comment]
Bugged.

**Comment by peterhurford** [comment]
Fixed on his RSS but I think it will only fix future links and not repair old ones (since the one on the EA forum is still broken).

That's fine enough with me, so I'll close this.
