### ISSUE TITLE
Add one simple line to <head> to show EA Newsletter signup

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#66]
The line is `<script src="//load.sumome.com/" data-sumo-site-id="2115f2f4b9e86f1f2e73c48fb896958ad06ae47bfb80face9329b72cb21fca6c" async="async"></script>`.

I've tested this, and it's thoroughly approved, and quite high priority. Would you be able to do it soon @patbl, and if so when by? I did try finding templates myself quickly, but it's way too opaque for me to have time - it almost looks as if the HTML is created programmatically in /r2/r2/public/static/protoplasm/livegrid/livegrid.js, and Trike had described something like that to me, but I can't quite believe it!

**Comment by patbl** [comment]
It's done: https://github.com/tricycle/eaforum/pull/45

Happy Brexit!

**Comment by tog22** [comment]
Noooooo! 😱  (To Brexit, not the PR - thanks for that. I'm just chasing Trike.)
