### ISSUE TITLE
Strange behavior in replying to downvoted comments

### ISSUE THREAD

**Issue by michaeldickens** [tog22/eaforum#69]
<img width="623" alt="screen shot 2016-08-18 at 6 14 23 pm" src="https://cloud.githubusercontent.com/assets/414378/17795738/c9819828-656f-11e6-88bc-3d8d0edd4f63.png">
I got this warning when trying to reply to a comment with 0 points. I suspect this is because the comment I wanted to reply to was itself a reply to a comment with negative points. Is this the intended behavior? It seems wrong to me.

**Comment by patbl** [comment]
It looks as though it checks each parent of your reply for downvoting and applies the penalty if any of the ancestors was sufficiently downvoted:

https://github.com/patbl/eaforum/blob/master/r2/r2/models/link.py#L1086..L1090
https://github.com/patbl/eaforum/blob/master/r2/r2/models/link.py#L965..L973

It seems to be the behavior intended by the author, but I don't know whether it's a good idea.

**Comment by peterhurford** [comment]
I'm going to close this issue since it's not technically a bug, but if enough people don't like it we could reopen this as a feature request.
