### ISSUE TITLE
default inline reply box size is too big on Android

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#7]

**Comment by arichard4** [comment]
What Android device does this fail on? Checking using Chrome's emulator seems to show it working OK for all the devices I checked.

**Comment by peterhurford** [comment]
@tog22 Can you look into Alex's comment?

**Comment by tog22** [comment]
I replied in the workathon - he's asking Ryan.

**Comment by arichard4** [comment]
@RyanCarey

**Comment by RyanCarey** [comment]
I can replicate it on Chrome's emumlator on at least iphone 4 and Nexus 4,
and probably on all of them. The problem is that you have an empty and
appropriately sized comment-box initially, but when you type in the first
letter, then the bottom of the box stretches down to cover up the 'comment'
button.

Ryan Carey | bioinformatics student | medical resident

**Comment by arichard4** [comment]
eaforum.css line 135:
.commentreply textarea {
    margin: 0 0 10px;
    width: 100%;
}

The textarea is contained in the content div, which is the entire vertical column that makes up the content/comments. This is constrained in main.css line 49 to be a fixed width of 695px, which is wider than phone screens. It scales correctly initially, but on text being entered it tries to scale the width out to 100% of 695 pixels, or wider than the screen; the width is not actually changed, but the height is scaled up by the same percentage as the width would be scaled up.

**Comment by tog22** [comment]
Nice, what will `@media (max-width: 959px)` apply to?

**Comment by arichard4** [comment]
It is effectively an if statement; the css inside it is executed if the entire document's max-width is less than 960px.

http://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by peterhurford** [comment]
@arichard4 Nice!  Make a PR? :+1:

**Comment by RyanCarey** [comment]
You guys can be proud of all the sweet improvements you've made. Best to
wait 'till they go live to announce them. If you want, Ali Woodman (who is
moderating currently) and I can write something nice about y'all ;)

Ryan Carey | bioinformatics student | medical resident

**Comment by tog22** [comment]
I'll create a PR for this - I almost have https://github.com/tog22/eaforum/commits/issue-1-for-pr ready for it (despite the name that covers this issue as well as #1 ).

**Comment by tog22** [comment]
@arichard4 - I assume I'll need to reopen this issue after PR https://github.com/tricycle/eaforum/pull/13 is merged?

**Comment by arichard4** [comment]
Possibly not; I would expect so, but my quick test showed this still being fixed under wrsaunde's edit

**Comment by tog22** [comment]
OK, can you test it on the live site after you see that PR gets merged (and deployed in the live HTML)?

**Comment by tog22** [comment]
(And reopen this issue yourself if need be.)

**Comment by arichard4** [comment]
Yes
