### ISSUE TITLE
ol tags not customizable by type

### ISSUE THREAD

**Issue by jayqui** [tog22/eaforum#70]
I submitted [a post](http://effective-altruism.com/ea/10u/film_as_an_ea_outreach_tool/) and wanted to customize the type of characters that would serve as bullets in some of its ordered lists. I changed the `type` attribute in the relevant `<ol>` tag to make it `<ol type="a">`, but this didn't trigger the expected change (e.g. [this fiddle](https://jsfiddle.net/mrjrx9g5/)).

**Comment by patbl** [comment]
Seems easy to fix: https://www.tinymce.com/docs/configure/content-filtering/#extended_valid_elements

My dev environment is jacked up, though, so it may be a while before I get around to doing any more work on the forum.
