### ISSUE TITLE
Pound sign formatting broken

### ISSUE THREAD

**Issue by Discordius** [tog22/eaforum#74]
It looks like there are some special character problems. I don't know exactly when they show up, but in this article the pound sign is broken: 

http://effective-altruism.com/ea/5e/efficient_charity_do_unto_others/#comments

**Comment by patbl** [comment]
To clarify, this refers to the symbol for the British pound, not the octothorp.

In case the article is edited, here's the relevant text:

>  campaign, eleven thousand British donors gave a total of ÂŁ550,000 to keep the famous painting "Blue Rigi" in a UK museum. If they had given that ÂŁ550,000 to buy better sanitation systems in African villages instead, the latest statistics suggest it would have saved the lives of about one thousand two hundred people from disease. Each individual $50 donation could have given a year of normal life back to a Third Worlder afflicted with a disabling condition like blindness or limb deformity..

**Comment by patbl** [comment]
The problem seems to be specific to that article. The text was probably copied from some other source and was mangled in the process. Here's what a test post looks like:

![poudns](https://cloud.githubusercontent.com/assets/1735266/19101472/7594dbc0-8a7d-11e6-86ac-df8df496fee0.png)

**Comment by Discordius** [comment]
Ah, I see. I guess we will ping Scott personally then (trying to fix the
formatting, since it's an article we link to reasonably often).
