### ISSUE TITLE
Fix open-thread sidebar link

### ISSUE THREAD

**Issue by patbl** [tog22/eaforum#84]
![screenshot 2016-12-30 16 42 20](https://cloud.githubusercontent.com/assets/1735266/21574820/f6630004-ceae-11e6-9410-8557cac42c3e.png)

It needs to match titles like this: http://effective-altruism.com/ea/15m/semiregular_open_thread_35/

It's still pointing to the September open thread.

Probably it could just point to the most-recent post with "open thread" in the title. That would be right most of the time.

Or we could get rid of the link altogether.

**Comment by tog22** [comment]
@georgiemallett is the one to coordinate with on this since she's on the EA Newsletter team and gets someone to post the open thread with the current newsletter's content each month, so she can specific what title/tags whoever she delegates this to uses.

**Comment by patbl** [comment]
Fixed by tricycle/eaforum#68.
