### ISSUE TITLE
"Recently on EA Blogs" is empty

### ISSUE THREAD

**Issue by peterhurford** [tog22/eaforum#86]

**Comment by RyanCarey** [comment]
It would helpful if any contributor, old or new, could fix this particular issue, since it's user-visible, and the handover to CEA is slowed by their busy-neses with YC!

**Comment by liavkoren** [comment]
I just got the website up and running locally last weekend, and I'll start working on the actual issue this coming weekend. Although if anyone wants to fix it before then, please feel free. : )

**Comment by RyanCarey** [comment]
Nice!

**Comment by RyanCarey** [comment]
According to a friend, Sam Eisenstat, the same bug is present on LessWrong!!!

**Comment by tog22** [comment]
@RyanCarey @patbl @peterhurford @liavkoren 

As I recall, we/I temporarily fixed this by removing the sidebar element. In the interest of having less to maintain, how about linking to Pablo Stafforini's http://eablogs.net/ ( https://impact.hackpad.com/Aggregator-for-recent-EA-blog-posts-d2WhcblcsUU )? Or making our own sidebar block which simply pulls from this at http://fetchrss.com/rss/589d19a28a93f88c6b8b456799635385451.xml ?

@liavkoren did you make any progress on this, or the forum generally?

**Comment by liavkoren** [comment]
Hi. Sorry for the delay replying. 
I haven't had a chance to touch the eaforum code since https://github.com/tricycle/eaforum/pull/70 was merged. 

I worked with https://pythonhosted.org/feedparser/ a few years ago, and remember it as being a good package for consuming RSS feeds. I'd be happy to work on this issue, and can probably get to it soon, but am also hesitant to give an concrete estimate -- life's been chaotic recently.

**Comment by tog22** [comment]
That's good enough for our approach to this project! Please assign yourself to it (I can't as I'm not connected to you on github), and assign it back to @peterhurford for reassignment if you make no progress for a month. 🙂

**Comment by liavkoren** [comment]
> Please assign yourself to it 

I can't. Is there an org I need to be added to?

**Comment by peterhurford** [comment]
@tog22 I'm not able to answer @liavkoren 's question -- I can't seem to figure out how to assign him to the issue either.

**Comment by tog22** [comment]
@liavkoren I've invited you, which should let you assign yourself after that

@peterhurford I did so at https://github.com/tog22/eaforum/settings/collaboration which I guess only I can have access to. For future repos made in the impct github org, or repos already in it, you'd add people via https://help.github.com/articles/inviting-users-to-join-your-organization/ (I don't have permissions to). But as already decided, let's not bother switching the EA Forum repo. 

On another note, apparently *this* is who we're dealing with. Are you comfortable with this @RyanCarey ? Normally no one knows you're a cat on the internet, but now it's out of the bag...

![img](https://image.prntscr.com/image/fe427cc8d2b04f16bc2b88b2035c0267.png)

**Comment by liavkoren** [comment]
*panics*..

**Comment by tog22** [comment]
You can always change it, but you'll forever be exposed here...

**Comment by tog22** [comment]
still cool to do this @liavkoren or have i scared you off? 😛 

#scaredycat

**Comment by liavkoren** [comment]
: ) Not scared off, just been hella slammed lately.

**Comment by tog22** [comment]
OK, would you be game @arichard4 or @patbl? If neither say yes you can assign someone else @peterhurford

**Comment by arichard4** [comment]
I'll take a preliminary look and get back to you Wednesday.

**Comment by tog22** [comment]
Awesome, thanks Alex
