### ISSUE TITLE
Petition to add spacing beneath each <li>

### ISSUE THREAD

**Issue by pbrietbart** [tog22/eaforum#87]
As title.

Reading large blocks of listed comments is an eyesore. See Kaj's [recent post](http://effective-altruism.com/ea/1b3/cognitive_sciencepsychology_as_a_neglected/) as an example.

Give < li > `padding-bottom: 15px;` and it would be much nicer on the eyes.

Many thanks.

**Comment by tog22** [comment]
Ha, we're very open to this sort of petition!

@patbl if you're up for it, please straw poll people in https://www.facebook.com/groups/dotimpact about this change, tagging @RyanCarey. you could mock it up with Chrome's Inspect Element and share a quick screenshot using https://docs.google.com/document/d/1SvQAlolfFopxO2Qyi8Hs7K1b81LAXM7oriiAblC7rIk/edit#heading=h.p7yrauovg9x0 

if you're not up for things like this, please always say ❤️  cc @peterhurford fyi

**Comment by patbl** [comment]
Here's a pull request with a screenshot: https://github.com/tricycle/eaforum/pull/71

I don't think it's worth asking people about minor style changes with other people if we're all fine with them. The forum isn't much to look at. We won't be ruining anybody's artistic vision.

**Comment by RyanCarey** [comment]
Looks great to me :)

**Comment by pbrietbart** [comment]
Perfect 👍
