### ISSUE TITLE
Filter out '&#...' from the links to recent blogs, perhaps just with regex.

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#9]
- Filter out '&#...' from the links to recent blogs, perhaps just with regex.

**Comment by peterhurford** [comment]
https://github.com/arichard4/eaforum/commit/b6f097a0e08a80a65771948dee1af028591b6d6d

**Comment by arichard4** [comment]
I've submitted a pull request. The problem is that 80K's feed had HTML character entities in the raw text; the solution was taken from here: http://stackoverflow.com/questions/7394748/whats-the-right-way-to-decode-a-string-that-has-special-html-entities-in-it

**Comment by peterhurford** [comment]
PR: https://github.com/tog22/eaforum/pull/14

**Comment by peterhurford** [comment]
Submitted to Trike: https://github.com/tricycle/eaforum/pull/7
